---
title: 'Project: Data Science'
author: "Sean E. Curl"
date: "April 4, 2018"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(readr)
library(tidyverse)
library(styler)
library(purrr)
library(ggthemes)
library(ggmap)
library(ggplot2)
library(ggthemes)
library(purrr)
library(ggrepel)
library(DT)
library(highcharter)
library("viridisLite")
library(countrycode)
```

### Load and Clean
```{r warning=FALSE}
dataset <- read_xlsx("./globalterrorismdb_0617dist.xlsx", col_types = "text")

terrorism <- dataset %>%
  select("Year" = iyear, 
         "Month" = imonth, 
         "Day" = iday, 
         "Country" = country_txt, 
         "Region" = region_txt, 
         "AttackType" = attacktype1_txt, 
         "Target" = target1, 
         "Killed" = nkill, 
         "Wounded" = nwound, 
         "Summary" = summary, 
         "Group" = gname, 
         "Target_Type" = targtype1_txt, 
         "Weapon_type" = weapsubtype1_txt, 
         "Motive" = motive,
         "City" = city,
         "lat" = latitude,
<<<<<<< HEAD
         "long" = longitude,
=======
         "lon" = longitude) %>%
  mutate(Killed = as.numeric(Killed),
         Wounded = as.numeric(Wounded),
<<<<<<< HEAD
         Casualties = Killed + Wounded) %>%
=======
         lat = as.numeric(lat),
         lon = as.numeric(lon)) %>%
=======
<<<<<<< HEAD
         "City" = city,
         "lat" = latitude,
         "lon" = longitude) %>%
=======
>>>>>>> d758fab117c0c8b10a431ec6be65c639204ecdc0
         "City" = city) %>%
  
  mutate(Killed = as.numeric(Killed),
<<<<<<< HEAD
         Wounded = as.numeric(Wounded), lat = as.numeric(lat), long = as.numeric(long)) %>%
=======
         Wounded = as.numeric(Wounded)) %>%
>>>>>>> 6a4bedf5bcb8bebfcfd97ab4f468bc6b7d6067ae
>>>>>>> f19bc5aa0c2fe237eef3d294a82c17cfd1772d28
>>>>>>> d758fab117c0c8b10a431ec6be65c639204ecdc0
  mutate(Casualties = Killed + Wounded) %>%
>>>>>>> 8fe029add2379ca6072238a8217310bf5124565d
  glimpse()

terrorism %>% 
  map_dbl(~sum(is.na(.)))
```
  
## High Impact Areas
```{r}
country_highest_attacks <- terrorism %>%
  group_by(Country) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  slice(1)

region_highest_attacks <- terrorism %>%
  group_by(Region) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  slice(1)

highest_killed <- terrorism %>%
  group_by(Year, Country, Killed) %>%
  summarise(max(Killed)) %>%
  arrange(desc(Killed)) %>%
  head(1)

paste("Country with Highest Terrorist Attacks:", country_highest_attacks$Country)
paste("Region with Highest Terrorist Attacks:", region_highest_attacks$Region)
paste("Maximum peopled killed in an attack are:", "In", highest_killed$Year, highest_killed$`max(Killed)`, "peopled died in",highest_killed$Country)
```
 
## Popular Attack Types
```{r}
attacking_methods <- terrorism %>%
  group_by(AttackType) %>%
  summarise(n = n()) %>%
  arrange(n) %>%
  ggplot(mapping = aes(reorder(AttackType, n), n, fill = AttackType)) + 
  geom_bar(stat = "identity", show.legend = FALSE) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Count") +
  xlab("Attack Type") + 
  ggtitle("Attacking Methods by Terrorists") +
  theme_bw() +
  coord_flip()

attacking_methods
<<<<<<< HEAD
=======
```
  
## Global Terror Maps
```{r include=FALSE, cache=FALSE}
Geo.Country = geocode(unique(terrorism$Country))

```

```{r warning=FALSE}
Geo.Country$Country = unique(terrorism$Country)
Geo.Country <- Geo.Country %>%
  select(Country, lon, lat) %>%
  arrange(Country)

graph_data <- terrorism %>%
  filter(Year == "1980") %>%
  group_by(Year, Country, lon, lat, Casualties) %>%
  summarise(total = sum(Casualties))

mp <- NULL
mapWorld <- borders("world", colour="gray50", fill="gray50")
mp <- ggplot() +  mapWorld +
  geom_point(data = graph_data, mapping = aes(x=lon, y=lat, size = total, color = "#000099"), show.legend = FALSE) +
  theme_classic() +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank()) +
  ggtitle("Casualties by Country since 1970")

mp
```
  
```{r}
test <- merge(Geo.Country, terrorism, by = "Country") %>%
  group_by(Group) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  slice(1:20)
>>>>>>> d758fab117c0c8b10a431ec6be65c639204ecdc0

attacking_methods_table <- terrorism %>%
  group_by(AttackType) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

print(attacking_methods_table)
```

```{r Some Basic Analysis}
# Number of Terrorist Acivities Year
count <- terrorism %>%
  group_by(Year) %>%
  summarise(n = n()) %>%
  mutate(Year = as.numeric(Year))

ggplot(count, 
       aes(x = Year, 
           y = n, fill = factor(Year))) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  xlab("Year") +
  ylab("Count") +
  ggtitle("Worldwide: Number of Terrorist Acivities Each Year") +
  scale_x_continuous(breaks = c(1970, 1980, 1990, 2000, 2010, 2020), limits = c(1970, 2016)) +
  theme_bw() +
  coord_flip()

# Number of Terrorist Acivities, Top Six Years
count2 <- terrorism %>%
  group_by(Year) %>%
   summarise(n = n()) %>%
  arrange(desc(n))

print(head(count2))
```

```{r}
# Terrorist Targets by Count
count <- terrorism %>%
  group_by(Target_Type) %>%
  summarise(n = n())

ggplot(count, 
       aes(reorder(x = Target_Type, n), 
           y = n, fill = factor(Target_Type))) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  xlab("Target Type") +
  ylab("Count") +
  ggtitle("Worldwide: Terrorist Targets by Count") +
  theme(axis.text.x=element_text(angle = 90, hjust =1)) +
  theme_bw() +
  coord_flip()

count2 <- terrorism %>%
  group_by(Target_Type) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

print((count2))
```

```{r}
# Terrorist Attacks by Region, Bar Chart
count <- terrorism %>%
  group_by(Region) %>%
  summarise(n = n())

ggplot(count, 
       aes(reorder(x = Region, n), 
           y = n, fill = factor(Region))) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  xlab("Region") +
  ylab("Count") +
  ggtitle("Worldwide: Terrorist Attacks by Geographic Region") +
  theme(axis.text.x=element_text(angle = 90, hjust =1)) +
  theme_bw() +
  coord_flip()

count2 <- terrorism %>%
  group_by(Region) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

print((count2))

```

```{r}
# Terrorist Attacks by Region, Line Chart
Attack.region.count <- terrorism %>%
  group_by(Region, Year) %>%
  summarise(total = sum(n())) %>%
  mutate(Year = as.numeric(Year))

ggplot(Attack.region.count, 
       aes(x = Year, 
           y = total, colour = Region, group = Region)) +
  geom_line(stat = "identity") +
  xlab("Year") +
  ylab("Count") +
  ggtitle("Terrorist Attacks by Region") +
  scale_x_continuous(breaks = c(1970, 1980, 1990, 2000, 2010, 2020), limits = c(1970, 2016)) +
<<<<<<< HEAD
  theme(axis.text.x=element_text(angle = 90, hjust =1)) +
  theme_classic()
=======
  theme_bw()
>>>>>>> 8fe029add2379ca6072238a8217310bf5124565d
```

```{r}
# Terrorist Attacks by Group
count <- terrorism %>%
  filter(!Group == "Unknown" & Group %in% c("Taliban", "Shining Path (SL)",
                                            "Islamic State of Iraq and the Levant (ISIL)", "Farabundo Marti National Liberation Front (FMLN)", "Al-Shabaab",
                                            "Irish Republican Army (IRA)",
                                            "Revolutionary Armed Forces of Colombia (FARC)",
                                            "New People's Army (NPA)",
                                            "Kurdistan Workers' Party (PKK)",
                                            "Boko Haram")) %>%
  group_by(Group, Year) %>%
  summarise(total = n()) %>%
  mutate(Year = as.numeric(Year))

ggplot(count, 
       aes(x = Year, 
           y = total, colour = Group, group = Group)) +
  geom_line(stat = "identity") +
  xlab("Year") +
  ylab("Count") +
  ggtitle("Terrorist Attacks by Group") +
  scale_x_continuous(breaks = c(1970, 1980, 1990, 2000, 2010, 2020), limits = c(1970, 2016)) +
  theme_bw()

# Top Six Groups, Terrorist Attacks by Region
count3 <- terrorism %>%
  filter(!Group == "Unknown") %>%
  group_by(Group, Region) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

print(head(count3))
```

## Global Terror Maps
```{r include=FALSE, cache=FALSE}
  GTA_graph_data <- terrorism %>%
      group_by(Country, long, lat, Casualties) %>%
      summarise(total = sum(Casualties))

```

```{r warning=FALSE}
    mp <- NULL
    mapWorld <- borders("world", colour="gray50", fill="gray50")
    mp <- ggplot() +  mapWorld +
      geom_point(data = GTA_graph_data, mapping = aes(x=long, y=lat, 
                                                        group = Country, size = total, color = "red"), 
                 show.legend = FALSE) +
      theme_classic() +
      theme(axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            axis.line = element_blank()) +
      ggtitle(paste("Global Terror Attacks:"))
    mp
```
  
```{r}
test <- terrorism %>%
  filter(!Group == "Unknown") %>%
  group_by(Group) %>%
  summarise(total = n()) %>%
  arrange(desc(total)) %>%
  slice(1:10)

graph_data1 <- terrorism %>%
  filter(!Group == "Unknown" & Group %in% c("Taliban", "Shining Path (SL)",
                                            "Islamic State of Iraq and the Levant (ISIL)", "Farabundo Marti National Liberation Front (FMLN)", "Al-Shabaab",
                                            "Irish Republican Army (IRA)",
                                            "Revolutionary Armed Forces of Colombia (FARC)",
                                            "New People's Army (NPA)",
                                            "Kurdistan Workers' Party (PKK)",
                                            "Boko Haram")) %>%
  group_by(Group, long, lat) %>%
  summarise(total = n()) %>%
  arrange(desc(total))


lp <- NULL
mapWorld <- borders("world", colour="gray50", fill="gray50")

lp <- ggplot(data = graph_data1, mapping = aes(x=long, y=lat)) +  mapWorld +
  geom_point(aes(color = Group)) +
# geom_label_repel(aes(label = Group), data = graph_data1) +
  theme_classic() +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank()) +
  ggtitle("Events by the Top 10 Terrorist Organizations since 1970")
lp
```

```{r Terroist Attacks in USA}
# Terrorist Attacks by City in USA
count <- terrorism %>%
    filter(City %in% c("New York City", "Oklahoma City",
                                            "The Dalles", 
                                            "Arlington", 
                                            "West",
                                            "Boston",
                                            "Atlanta",
                                            "Orlando")) %>%
  group_by(City) %>%
  summarise(total = sum(n())) %>%
  arrange(desc(total))


ggplot(count, 
       aes(x = City, 
           y = total, colour = City, group = City )) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  xlab("City Name") +
  ylab("Count") +
  ggtitle("Terrorist Attacks in Top U.S. City with New York City") +
  theme_bw()

print(count)

highest_killed_USA <- terrorism %>%
  filter(Country == "United States")  %>%
  group_by(Year, City, Casualties) %>%
  summarise(total = sum(Casualties)) %>%
  arrange(desc(total)) %>%
  head(14)

data.frame(highest_killed_USA)

# WITHOUT NEW YORK
count <- terrorism %>%
    filter(City %in% c("Oklahoma City", "Hyder", "Shanksville",
                                            "The Dalles", 
                                            "Arlington", 
                                            "West",
                                            "Boston",
                                            "Atlanta",
                                            "Orlando")) %>%
  group_by(City) %>%
  summarise(total = sum(n())) %>%
  arrange(desc(total))

ggplot(count, 
       aes(x = City, 
           y = total, colour = City, group = City )) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  xlab("City Name") +
  ylab("Count") +
  ggtitle("Terrorist Attacks in Top U.S. City, Minus New York City") +
  theme_bw()

print(count)

highest_killed_USA <- terrorism %>%
  filter(Country == "United States")  %>%
  filter(!City == "New York City")  %>%
  group_by(Year, City, Casualties) %>%
  summarise(total = sum(Casualties)) %>%
  arrange(desc(total)) %>%
  head(14)

data.frame(highest_killed_USA)
```
